# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181

